export const items = [
    {id : Math.random() , title : "لحسة" , description : "بيض,جبن,سطلة,بهارات معمول على الطاولة" , price : "14 شيكل" , category : "فطار" , imgUrl :"lahsa.png"},
    {id : Math.random() , title : "بوكس شباتي" , description : "بوكس شباتي بحشوات مميزة و لذيذة 16 ساندوتش" , price : "69 شيكل" , category : "فطار" , imgUrl :"box.png"},
    {id : Math.random() , title : "صحن شكشوكة" , description : "صحن شكشوكة" , price : "11 شيكل" , category : "فطار" , imgUrl :"Shakshuka.png"},
    {id : Math.random() , title : "فول جرة" , description : "فول ابيض مع زيت زيتون و كمون" , price : "8 شيكل" , category : "فطار" , imgUrl :"fool.png"},
    {id : Math.random() , title : "صحن بيض" , description : "بيض مقلي او مسلوق" , price : "14 شيكل" , category : "فطار" , imgUrl :"egg.png"},
    {id : Math.random() , title : "شاورما عربي لحم" , description : "شاورما اللحم بخبز الصاج ومقطعه مع صوص الحمص والمخلل والبطاطس والسلطه  وصوص اسبايسي" , price : "22 شيكل" , category : "غداء" , imgUrl :"shawrma.png"},
    {id : Math.random() , title : "برجر" , description : "برجر" , price : "20 شيكل" , category : "غداء" , imgUrl :"burger.jpeg"},
    {id : Math.random() , title : "بطاطس حارة" , description : "بطاطس مع شرائح شاورما الدجاج  - صوص اسبايسي مع الكزبرة والبصل الاخضر " , price : "16 شيكل" , category : "غداء" , imgUrl :"hot fries.png"},
    {id : Math.random() , title : "بروستد" , description : "4 قطع ,بطاطس مقلي , صوص ثوم   , حمص ,  مخلل " , price : "20 شيكل" , category : "غداء" , imgUrl :"broasted.png"},
    {id : Math.random() , title : "برجر شكشوكة" , description : "شكشوكة-جبن-صوص" , price : "11 شيكل" , category : "عشاء" , imgUrl :"Shakshuka Burger.png"},
    {id : Math.random() , title : "لحسة" , description : "بيض,جبن,سطلة,بهارات معمول على الطاولة" , price : "14 شيكل" , category : "عشاء" , imgUrl :"lahsa.png"},
    {id : Math.random() , title : "بوكس شباتي" , description : "بوكس شباتي بحشوات مميزة و لذيذة 16 ساندوتش" , price : "69 شيكل" , category : "عشاء" , imgUrl :"box.png"},
    {id : Math.random() , title : "صحن شكشوكة" , description : "صحن شكشوكة" , price : "11 شيكل" , category : "عشاء" , imgUrl :"Shakshuka.png"},
    {id : Math.random() , title : "فول جرة" , description : "فول ابيض مع زيت زيتون و كمون" , price : "8 شيكل" , category : "عشاء" , imgUrl :"fool.png"},
    {id : Math.random() , title : "صحن بيض" , description : "بيض مقلي او مسلوق" , price : "14 شيكل" , category : "عشاء" , imgUrl :"egg.png"},
    {id : Math.random() , title : "شاورما عربي لحم" , description : "شاورما اللحم بخبز الصاج ومقطعه مع صوص الحمص والمخلل والبطاطس والسلطه  وصوص اسبايسي" , price : "22 شيكل" , category : "عشاء" , imgUrl :"shawrma.png"},
    {id : Math.random() , title : "برجر" , description : "برجر" , price : "20 شيكل" , category : "عشاء" , imgUrl :"burger.jpeg"},
    {id : Math.random() , title : "بطاطس حارة" , description : "بطاطس مع شرائح شاورما الدجاج  - صوص اسبايسي مع الكزبرة والبصل الاخضر " , price : "16 شيكل" , category : "عشاء" , imgUrl :"hot fries.png"},
    {id : Math.random() , title : "بروستد" , description : "4 قطع ,بطاطس مقلي , صوص ثوم   , حمص ,  مخلل " , price : "20 شيكل" , category : "عشاء" , imgUrl :"broasted.png"},
    {id : Math.random() , title : "برجر شكشوكة" , description : "شكشوكة-جبن-صوص" , price : "11 شيكل" , category : "عشاء" , imgUrl :"Shakshuka Burger.png"},
]